### ISSUE TITLE
Availability times displayed changes when click in and out of Availability tab

### ISSUE THREAD

**Issue by rwood-moz** [thunderbird/appointment#1206]
**Describe the bug**
When I leave the `Availability` tab and then return, the availability start/end times displayed have changed to different values. The values aren't actually applied and refreshing the page restores the start/end times to their correct values.

**To Reproduce**
Sign into the Appointment dashboard (with a calendar already connected and Availability setup) then:

- Click on the `Availability` tab
- Note the values displayed for availability start/end times
- Without making any changes, click on the `Dashboard` tab
- Then click back on the `Availability` tab
- Note the start/end time values displayed have changed
- Refresh the browser page and note the start/end time values change again back to their correct values

**Expected behavior**
Expect the availability start/end times to be correct and not change when leave/go back into the page.

**Actual behavior**
Availability start/end times displayed are changed (although not actually applied which is good).

**Screenshots**
Availability when first sign in:
<img width="584" height="202" alt="Image" src="https://github.com/user-attachments/assets/6c05ba06-9d62-4bf3-9aad-5cfe2607a811" />

After going to Dashboard tab then back to Availability tab 1st time:
<img width="583" height="205" alt="Image" src="https://github.com/user-attachments/assets/e812da8a-e395-457a-b04e-04fefa3f6c0e" />

After going to Dashboard tab then back to Availability tab 2nd time:
<img width="583" height="202" alt="Image" src="https://github.com/user-attachments/assets/17c0aed3-53bc-4d6b-ae1c-9a343f273626" />

After refreshing Availability page:
<img width="583" height="202" alt="Image" src="https://github.com/user-attachments/assets/8121157d-293e-434d-9c69-0a9f8e58dea5" />

**System (please complete the following information):**

- OS: MacOS Sequoia
- Browser Version: Firefox 142.0

**Comment by sohmc** [comment]
Came here to report the same issue.  It looks like the Time Zone is not taken to account when you save your preferences and will convert the time that you entered to UTC time.  When you click back into "Availability", the times are displayed based on UTC time, but are correct.

**Comment by rwood-moz** [comment]
Ah, interesting, thank you for your input @sohmc, much appreciated!

**Comment by rwood-moz** [comment]
Verified on my local stack (with updated main) and on stage that this is now fixed by #1242. Nice!

**Comment by sohmc** [comment]
I see that #1242 has been merged but I still see the same issue on my side.  Has it been deployed?

**Comment by rwood-moz** [comment]
> I see that [#1242](https://github.com/thunderbird/appointment/pull/1242) has been merged but I still see the same issue on my side. Has it been deployed?

No this has not been deployed to production yet.
