### ISSUE TITLE
All day events bleed into the next day 

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#580]
**Describe the bug**
All day events bleed into the next day

**To Reproduce**

1. Create an all day event on Friday in your calendar (in my case it was an all day OOO event on gcal)
2. Go to calendar in appointment.day
3. Observe that the event shows on both Friday and Saturday (depending on timezones)

**Expected behavior**
End dates are exclusive, and date-only events are in floating timezone. Make sure they are displayed as such.

**Actual behavior**
Event appears in multiple days 

**Screenshots**
![image](https://github.com/user-attachments/assets/c55ea63f-2f68-498d-9abf-8e810f8b4c26)

**System (please complete the following information):**

- OS: macOS
- Browser Version Firefox Nightly

**Additional context**
This happens in a few different calendar views

**Comment by kewisch** [comment]
Sounds like the same issue! This isn't the event on the PTO calendar, but rather a custom "Out of Office" event I set for all day Friday so my calendar is blocked for the rest of Mozilla. I was wrong on this being a date-only event, it appears that Google makes this a midnight to midnight event in your timezone when exporting via ICS (and also via the API).

```
BEGIN:VEVENT
CREATED:20240603T122629Z
LAST-MODIFIED:20240603T123049Z
DTSTAMP:20240603T123049Z
UID:20t8vd6tshj89ek6tsoohg4h69@google.com
SUMMARY:Wellbeing Friday
STATUS:CONFIRMED
ORGANIZER;CN=Unknown Organizer:mailto:unknownorganizer@calendar.google.com
ATTENDEE;CN=me@thunderbird.net;PARTSTAT=ACCEPTED;CUTYPE=INDIVIDUAL;ROL
 E=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:me@thunderbird.net
RRULE:FREQ=WEEKLY;BYDAY=FR;UNTIL=20240809T215959Z;WKST=SU
DTSTART;TZID=Europe/Berlin:20240705T000000
DTEND;TZID=Europe/Berlin:20240706T000000
CLASS:PUBLIC
SEQUENCE:0
TRANSP:OPAQUE
END:VEVENT
```
If you've fixed timezone conversion, then it should work.

**Comment by MelissaAutumn** [comment]
Hey there @kewisch!

I haven't had a chance to test this, but I've just pushed up the latest changes to production. Can you give it another try?

Thanks!

**Comment by kewisch** [comment]
Sorry for the delay, my gh notifications are a mess. I tried and still see this for those events:

![image](https://github.com/user-attachments/assets/a6562806-c6a6-4066-b5f7-e0c8686619d9)

**Comment by devmount** [comment]
This should be fixed with #1720 now. Although this issue is very old, might be worth testing again once released.

**Comment by rtanglao** [comment]
* In Zendesk ticket [6606](https://tbpro.zendesk.com/agent/tickets/6606), the all-day events are showing up at 5p.m. the previous day e.g. if it's all day July 11, it shows up as 5pm. to 5pm of the previous day in this case July 10, 2026. cc/ @davinotdavid @kewisch 

### Steps To Reproduce:

1. Create an All-Day event in the nemo@thundermail.com Thundermail calendar using Thunderbird. Let's call this `Event1` and let's say it's July 11
2. The event doesn't show up in Appointment
3. Change the availability of Event1 from Free/Available to Busy using the Options menu in Thunderbird

<img width="427" height="101" alt="Image" src="https://github.com/user-attachments/assets/be054199-169b-4124-9581-f8da43a2445b" />

### Expected
* Event1 shows up as an all day event for the day, July 11

### Actual
* Event1 shows up in Appointment but with the bug noted by the ZD ticket creator. It starts at 5p.m of the previous day and ends at 5p.m of the previous day in Event1's case July 10, 2026 5pm to July 10 5pm

#### Tool Tip

<img width="710" height="252" alt="Image" src="https://github.com/user-attachments/assets/fe5ee01d-895e-44d6-bb89-82b64aa16a2e" />

#### Grid view
<img width="292" height="508" alt="Image" src="https://github.com/user-attachments/assets/899e9e1a-c692-46c9-9061-82f75fd2e0a4" />

## ICS File

```ics
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20260707T040449Z
LAST-MODIFIED:20260707T040657Z
DTSTAMP:20260707T040657Z
UID:5a98a30f-fa32-4bc8-bda2-aa5279353ee0
SUMMARY:580 test all-day event nemo
DTSTART;VALUE=DATE:20260711
DTEND;VALUE=DATE:20260712
TRANSP:OPAQUE
X-MOZ-GENERATION:1
END:VEVENT
END:VCALENDAR
```

**Comment by devmount** [comment]
@rtanglao I believe this might be outdated data. All day events shouldn't show up in the hours-grid at all anymore but only on top of the corresponding day column, as shown here:

<img width="1075" height="691" alt="image" src="https://github.com/user-attachments/assets/bce3e036-8695-4a75-8a0e-11a24b67283b" />

This was part of the release one week ago. Can you confirm, that this still happens after the last release?

**Comment by rtanglao** [comment]
@devmount i AND the customer in ZD ticket [6606](https://tbpro.zendesk.com/agent/tickets/6606)
 am using whatever is in production on appointment.tb.pro. Perhaps your fix was never deployed? Screenshot:

<img width="1246" height="635" alt="Image" src="https://github.com/user-attachments/assets/6d448be8-61d2-444f-b1c7-9d61a6eca7b5" />

**Comment by devmount** [comment]
Thank you @rtanglao for the confirmation! I'll check the ICS file you gave, maybe I manage to reproduce that. I'll also cut a ticket for displaying the current Appointment version in the frontend, maybe that saves us some released/not-released confusion in the future 😇

**Comment by devmount** [comment]
@rtanglao I tested this locally with the exact event you gave in the ICS file, and it worked how it's supposed to be:

<img width="1662" height="729" alt="Image" src="https://github.com/user-attachments/assets/79480029-1838-4766-addc-cb6066bc5429" />

The only explanation I have is, that the Appointment app under appointment.tb.pro does not have the fix installed. We'll investigate.

**Comment by belcirelk** [comment]
I have reported this bug, please see the video to better understand.

https://github.com/user-attachments/assets/16e9efec-35d3-48af-b959-1f033b808e59

**Comment by devmount** [comment]
Thanks so much, Eric! No I can finally reproduce that issue!! 🙌🏻 

<img width="763" height="531" alt="Image" src="https://github.com/user-attachments/assets/fe4ed7ff-6ecd-4352-8d00-3da23e60ca92" />

**Comment by devmount** [comment]
Ok after some digging, I believe this is an issue with the Thundermail calendar returning the all-day event start as datetime instead of date.

<details><summary>Technical details</summary>

This is the answer we get from a Nextcloud CalDAV calendar:

```
https://nextcloud.test....:443 "REPORT /remote.php/dav/calendars/.../personal/ HTTP/1.1" 207 None

<VEVENT| [<UID{}5a98a30f-fa32-4bc8-bda2-aa5279353ee0>, <DTSTART{'VALUE': ['DATE']}2026-07-11>, <DTEND{'VALUE': ['DATE']}2026-07-12>, <CREATED{}2026-07-07 04:04:49+00:00>, <DTSTAMP{}2026-07-07 04:06:57+00:00>, <LAST-MODIFIED{}2026-07-07 04:06:57+00:00>, <SUMMARY{}580 test all-day event nemo>, <TRANSP{}OPAQUE>, <X-MOZ-GENERATION{}1>]>
```

and this is the answer from a Thundermail CalDAV calendar:

```
https://mail.thundermail.com:443 "REPORT /dav/cal/.../default/ HTTP/1.1" 207 710

<VEVENT| [<UID{}f0df6fe8-4479-477e-b5a5-fd33644714eb>, <DTSTART{}2026-07-10 00:00:00+00:00>, <DTEND{}2026-07-11 00:00:00+00:00>, <DTSTAMP{}2026-07-08 18:43:55+00:00>, <LAST-MODIFIED{}2026-07-08 18:43:55+00:00>, <SUMMARY{}All day test>, <TRANSP{}OPAQUE>, <X-MOZ-GENERATION{}1>]>
```

For some reason, Thundermail returns the `DTSTART` of all day events as normal datetime events, a date with time 00:00. Unfortunately this is exactly how we determine if this is an all day event or not, since there is no dedicated attribute for that (`all_day = not isinstance(start, datetime)`) and seems to be the standard way to do this.

So I currently see no way to solve this in Appointment.

</details>

@davinotdavid @kewisch How do we proceed on this? Is there a way to fix this in Thundermail land?

**Comment by rtanglao** [comment]
* So my  ICS file shows: 
```ics
DTSTART;VALUE=DATE:20260711
DTEND;VALUE=DATE:20260712
```
* And CalLDAV is different?!? weird. file a bug in Stalwart?

**Comment by rtanglao** [comment]
* @devmount if you had followed my steps to reproduce and used Thundermail's calendar to test instead of NextCloud you would have reproduced this problem yesterday but no biggie, but please **read my steps to reproduce next time and follow them exactly**
* no disrespect intended :-) This is yet more proof we should have professional QA e.g. SoftVision. Support and engineering folks aren't great at QA. I am terrible at QA but my joke is "support is QA for release" :-)

**Comment by rtanglao** [comment]
* For posterity, I made a video showing the bug  and it's on google drive and public: [2026-07-08-appointment-issue-580-all-day-event-5pm](https://drive.google.com/file/d/1HKosF6VboY6gs8mY6KNPWpSZIH2q6UGn/view?usp=drive_link)
* I am sure @belcirelk 's is smaller. Mine is 253MB :-) ooops!

**Comment by belcirelk** [comment]
@devmount The public booking page seems to handle the data correctly on my side with the same data, the calendar is not available the full day. Maybe the solution is already there in this part of the code.

**Comment by rtanglao** [comment]
@devmount @davinotdavid Thundermail subscribers keep asking if this is fixed :-) Any momentum forward?

**Comment by davinotdavid** [comment]
@rtanglao even though this seems to be an inconsistency / bug in the Stalwart side of things, I was chatting with @devmount about potential workarounds and he is evaluating what's best for this particular case while this is not solved upstream.

**Comment by devmount** [comment]
@belcirelk Great idea, the public booking page and the dashboard share the same backend code for the calendar event retrieval though. I don't know your concrete availability settings, but I can assume from your video, that those are set from 9am to 4pm. Since the public booking page only shows blocked areas and no single events, there could be the impression that it works, but it's only the all-day event spanning all over the available time frame.

With #1744 we implemented a workaround tailored to this issue and Tundermail as CalDAV provider in particular. This will be part of the next release - let's see if that fixes things for the time being and hope, that maybe sth can be found in Thundermail land / Stalwart.

**Comment by davinotdavid** [comment]
@belcirelk Updating here, the workaround made by @devmount has been pushed to production so may I ask you to try it to see if it is fixed on your end? Thank you 🙏

**Comment by belcirelk** [comment]
@davinotdavid @devmount It works on my side too. Thanks a lot!

**Comment by davinotdavid** [comment]
Awesome! Kudos to @devmount for the fix, that was a tricky one! 👏 🎉 

I am closing this issue but feel free to reopen in case it happens again. Thanks all!
